move_towards_point(oPlayer.x+random_range(-32,32),oPlayer.y+random_range(-32,32),random_range(3,5));
image_angle = point_direction(x,y,oPlayer.x,oPlayer.y);
gthsp = hspeed;
gtvsp = vspeed;
hsp = 0;
vsp = 0;
hspeed = 0;
vspeed = 0;
time = 0;
sprite_index = choose(sBullet,sBullet1);
image_xscale = 0.35;
image_yscale = 0.35;
image_blend = instance_nearest(x,y,oBad).image_blend;
sound(laser);